repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: ".tx/config"
    -   id: flake8
        args:
        - --exclude=*/*migrations/*, testproject/testproject/settings/*
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: end-of-file-fixer
        exclude: ".tx/config"
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
    -   id: reorder-python-imports
