# Because Python 3.6 is available on GCE
dist: trusty

language: python
cache: pip

python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - LINT="yes"
  - DJANGO="1.11"
  - DJANGO="2.0"

matrix:
  exclude:
  - python: "3.4"
    env: LINT="yes"
  - python: "3.5"
    env: LINT="yes"
  - python: "3.6"
    env: LINT="yes"

addons:
  apt:
    packages:
      - libjpeg8
      - libjpeg8-dev

install:
  - pip install tox\>=2.1 tox-travis codecov

script:
  - tox

notifications:
  irc:
    - "irc.freenode.org#django-wiki"

after_success:
  - codecov
